# Generated by Django 5.1.7 on 2025-06-02 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('REPAIR', 'Yêu cầu sửa chữa'), ('ISSUE', 'Báo cáo sự cố')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chưa xử lý'), ('RESOLVED', 'Đã xử lý')], default='PENDING', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
