# Generated by Django 5.1.7 on 2025-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_survey_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='core.surveyquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('student', 'notification')},
        ),
    ]
