# Generated by Django 5.1.7 on 2025-06-03 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinoutlog',
            options={'ordering': ['-check_time']},
        ),
        migrations.RemoveField(
            model_name='checkinoutlog',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='checkinoutlog',
            name='check_out_time',
        ),
        migrations.AddField(
            model_name='checkinoutlog',
            name='check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkinoutlog',
            name='qr_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkinout_logs', to='core.qrcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinoutlog',
            name='status',
            field=models.CharField(choices=[('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinoutlog',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('date',)},
        ),
        migrations.AddIndex(
            model_name='checkinoutlog',
            index=models.Index(fields=['student', 'date'], name='core_checki_student_81cedc_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinoutlog',
            index=models.Index(fields=['check_time'], name='core_checki_check_t_8220fd_idx'),
        ),
    ]
